<a href="https://colab.research.google.com/github/gauthiermartin/pytorch-deep-learning-course/blob/dev/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as p
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu118


In [4]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors


Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html?highlight=torch+tensor#torch.Tensor

In [4]:
## Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int

scalar.item()

7

In [9]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [2, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 6, 9],
        [2, 4, 5]])

# Tensor Playground

##  With a single scalar

In [24]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [17]:
# See numbers contained in the tensor
scalar.item()

1

In [23]:
# See dimensions of the tensor
scalar.dim()

0

In [22]:
# Display the shape of the tensor
scalar.size()

torch.Size([])

## Vector

In [26]:
vector = torch.tensor([1, 2, 3])
vector

tensor([6, 6, 6])

In [29]:
# Display dimensions dim/ndim of the tensor
vector.dim()

1

In [30]:
# Display the size / shape of the tensor
vector.size()

torch.Size([3])

## Matrix

In [33]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
# Display the dim/ndim of the tensor
matrix.dim()

2

In [36]:
# Display the size / shape of the tensor
matrix.shape

torch.Size([2, 3])

## Tensor

In [37]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
# Display the dimensions dim/ndim of the tensor
tensor.ndim

2

In [41]:
# Display the size / shape of the tensor
tensor.shape

torch.Size([3, 3])

In [43]:
# Display the nth row of the tensor
tensor[0]

tensor([1, 2, 3])

In [46]:
# Display the the xy(ij) element of the tensor
tensor[0][1]

tensor(2)

In [47]:
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ],
                       [[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
# Display the dimensions dim/ndim of the tensor
tensor.ndim

3

In [49]:
# Display the size / shape of the tensor
tensor.shape

torch.Size([2, 3, 3])

In [52]:
# Display the size / shape of the tensor
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# Display the the xyz (ijk) element of the tensor
tensor[0][0][1]

tensor(2)

# Lesson Learns


*   Scalar : a single number           | Dimensions : 0
*   Vector : a number with a direction | Dimensions : 1
*   Matrix : a 2-dimensional array of numbers | Dimensions : 2
*   Tensor : a n-dimensional array of numbers

* dim() / ndim => Numbers of dimensions of the tensor (Visualize: # of open or close sqaure brackets in a tensor)

* size() / shape => Size of the tensor (Visualize: Tuple of row, column count)




## Random tensors

Why random tensors ?

Random tensors are important because of the way many neural networks learn is that they start with tensors full of randoms numbers and then adjust those random numbers to better represent the data.

`Start with random tensors -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=torch+rand#torch.rand

In [64]:
# Create a random tensor of size / shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9648, 0.2810, 0.8243, 0.9894],
        [0.5419, 0.4144, 0.0293, 0.6236],
        [0.7034, 0.8749, 0.5854, 0.2664]])

In [65]:
random_tensor.ndim

2

In [67]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)