<a href="https://colab.research.google.com/github/gauthiermartin/pytorch-deep-learning-course/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [10]:
# Import torch
import torch
# Create random tensor
tensor_A = torch.rand(7,7)
tensor_A.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
tensor_B = torch.rand(1, 7)
# Perform matrix multiplication
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.8249],
        [2.3089],
        [2.6509],
        [1.5015],
        [2.0858],
        [2.0102],
        [2.9746]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
import torch
# Set manual seed
SEED = 0
# Create two random tensors
torch.manual_seed(0)
tensor_C = torch.rand(7, 7)

torch.manual_seed(0)
tensor_D = torch.rand(1, 7)
# Matrix multiply tensors
result_tensor = torch.matmul(tensor_C, tensor_D.T)
result_tensor, result_tensor.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
gpu_tensor_A = torch.rand(size=(2,3), device=device)
gpu_tensor_B = torch.rand(size=(2,3), device=device)

In [22]:
print(gpu_tensor_A, gpu_tensor_A.shape)
print(gpu_tensor_B, gpu_tensor_B.shape)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') torch.Size([2, 3])
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0') torch.Size([2, 3])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
tensor_AB = torch.matmul(gpu_tensor_A, gpu_tensor_B.T)
tensor_AB

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [26]:
# Find max
max = tensor_AB.max()
# Find min
min = tensor_AB.min()
print(f"Max: {max}, Min: {min}")

Max: 0.7667766809463501, Min: 0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
max_index = tensor_AB.argmax()
# Find arg min
min_index = tensor_AB.argmin()

print(f"Index of Max: {max_index}, Index of min: {min_index}")

Index of Max: 1, Index of min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed
torch.manual_seed(666)
torch.cuda.manual_seed(666)
# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)
random_tensor, random_tensor.shape
# Remove single dimensions
new_tensor = random_tensor.squeeze()
# Print out tensors and their shapes

print(random_tensor, random_tensor.shape)
print(new_tensor, new_tensor.shape)

tensor([[[[0.3119, 0.2701, 0.1118, 0.1012, 0.1877, 0.0181, 0.3317, 0.0846,
           0.5732, 0.0079]]]]) torch.Size([1, 1, 1, 10])
tensor([0.3119, 0.2701, 0.1118, 0.1012, 0.1877, 0.0181, 0.3317, 0.0846, 0.5732,
        0.0079]) torch.Size([10])
