<a href="https://colab.research.google.com/github/gauthiermartin/pytorch-deep-learning-course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as p
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors


Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html?highlight=torch+tensor#torch.Tensor

In [ ]:
## Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int

scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [2, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 6, 9],
        [2, 4, 5]])

# Tensor Playground

##  With a single scalar

In [ ]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
# See numbers contained in the tensor
scalar.item()

1

In [ ]:
# See dimensions of the tensor
scalar.dim()

0

In [ ]:
# Display the shape of the tensor
scalar.size()

torch.Size([])

## Vector

In [ ]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [ ]:
# Display dimensions dim/ndim of the tensor
vector.dim()

1

In [ ]:
# Display the size / shape of the tensor
vector.size()

torch.Size([3])

## Matrix

In [ ]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Display the dim/ndim of the tensor
matrix.dim()

2

In [ ]:
# Display the size / shape of the tensor
matrix.shape

torch.Size([2, 3])

## Tensor

In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Display the dimensions dim/ndim of the tensor
tensor.ndim

2

In [ ]:
# Display the size / shape of the tensor
tensor.shape

torch.Size([3, 3])

In [ ]:
# Display the nth row of the tensor
tensor[0]

tensor([1, 2, 3])

In [ ]:
# Display the the xy(ij) element of the tensor
tensor[0][1]

tensor(2)

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ],
                       [[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]
                       ]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Display the dimensions dim/ndim of the tensor
tensor.ndim

3

In [ ]:
# Display the size / shape of the tensor
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
# Display the size / shape of the tensor
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Display the the xyz (ijk) element of the tensor
tensor[0][0][1]

tensor(2)

# Lesson Learns


*   Scalar : a single number           | Dimensions : 0
*   Vector : a number with a direction | Dimensions : 1
*   Matrix : a 2-dimensional array of numbers | Dimensions : 2
*   Tensor : a n-dimensional array of numbers

* dim() / ndim => Numbers of dimensions of the tensor (Visualize: # of open or close sqaure brackets in a tensor)

* size() / shape => Size of the tensor (Visualize: Tuple of row, column count)




## Random tensors

Why random tensors ?

Random tensors are important because of the way many neural networks learn is that they start with tensors full of randoms numbers and then adjust those random numbers to better represent the data.

`Start with random tensors -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=torch+rand#torch.rand

In [ ]:
# Create a random tensor of size / shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[5.2405e-01, 7.5044e-01, 5.1492e-02, 3.9016e-01],
        [5.9142e-01, 1.8163e-02, 5.1008e-01, 8.0305e-01],
        [8.6372e-02, 7.1454e-04, 8.7459e-01, 5.4556e-01]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a random size tensor of a desktop image (
# Note that I won't be using the `size=` parameter here
random_desktop_image_tensor = torch.rand((3, 1920, 1080))
random_desktop_image_tensor

tensor([[[0.1370, 0.1763, 0.4316,  ..., 0.3557, 0.5068, 0.5793],
         [0.9665, 0.6909, 0.1626,  ..., 0.7446, 0.4071, 0.9119],
         [0.9729, 0.6971, 0.8513,  ..., 0.0744, 0.0224, 0.6405],
         ...,
         [0.6024, 0.6930, 0.5703,  ..., 0.4420, 0.7635, 0.9272],
         [0.5419, 0.4798, 0.5385,  ..., 0.9507, 0.5260, 0.9141],
         [0.6391, 0.6231, 0.5678,  ..., 0.0277, 0.3180, 0.6453]],

        [[0.6914, 0.7929, 0.1574,  ..., 0.9080, 0.9814, 0.8488],
         [0.0851, 0.3470, 0.3969,  ..., 0.3774, 0.4959, 0.0649],
         [0.8063, 0.5144, 0.3913,  ..., 0.6134, 0.2183, 0.5525],
         ...,
         [0.0015, 0.3239, 0.1137,  ..., 0.0813, 0.7012, 0.3257],
         [0.9804, 0.8766, 0.1925,  ..., 0.8423, 0.2905, 0.5852],
         [0.8195, 0.5875, 0.2491,  ..., 0.9141, 0.5345, 0.0412]],

        [[0.7991, 0.3507, 0.7795,  ..., 0.9225, 0.0531, 0.4590],
         [0.6369, 0.2964, 0.6397,  ..., 0.3422, 0.2914, 0.8124],
         [0.4674, 0.3746, 0.6837,  ..., 0.9015, 0.8536, 0.

In [ ]:
random_desktop_image_tensor.shape, random_desktop_image_tensor.ndim

(torch.Size([3, 1920, 1080]), 3)

## Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Get the type of data stored in a tensor
ones.dtype

torch.float32

## Range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes (tensor attributes)

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch



1.   Tensors not the right datatype
2.   Tensors not the right shape
3.   Tensor not on the right device





In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

# Default dtype is float32

torch.float32

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,           # What datatypes is the data in the tensor (e.g. float32, float16)
                               device=None,          # What device is you tensor on CPU(cpu) or GPU(cuda), None => default="cpu"
                               requires_grad=False)  # Track gradiant or not
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1.   Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2.   Tensors not the right shape  - to get shape from a tensor, can use `tensor.shape`
3.   Tensor not on the right device - to get device froma tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2956, 0.7210, 0.3381, 0.0075],
        [0.0115, 0.6807, 0.6437, 0.1580],
        [0.4849, 0.6691, 0.4533, 0.7713]])

In [ ]:
# Find out details about it
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor : torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations includes:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add ten to it
tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways to perform multiplication in neural networks and deep learning :


1.   Element-wise multiplication with a scalar
2.   Matrix multiplication (dot product (a.b))

More information on multipling matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are **two main rules** that performing **matrix multiplication** needs to satisfy:
1. The **inner dimensions** must match :
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2.  The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`



In [ ]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.28 ms, sys: 31 µs, total: 1.31 ms
Wall time: 1.32 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 73 µs, sys: 8 µs, total: 81 µs
Wall time: 85.8 µs


tensor(14)

### One of the most common error in deep learning : shape errors


In [ ]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor issues, we can manipulate the shape of one of our tensor using **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multipling: {tensor_A.shape} @ {tensor_B.T.shape} <= inner dimensions must match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])

Multipling: torch.Size([3, 2]) @ torch.Size([2, 3]) <= inner dimensions must match

Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (Tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x)

tensor(1)

In [ ]:
# Find the max
torch.max(x)

tensor(91)

In [ ]:
# Find the mean
torch.mean(x)

RuntimeError: ignored

In [ ]:
# Find the mean - note: the `torch.mean()` function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
# Finding the positional min and max

In [ ]:
# Find the index of the min
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the index of the max
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, Stacking, Squeezing and Unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory of the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way)

In [4]:
# Let's create tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [6]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [7]:
# Change the view
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [9]:
# Changing z changes x (because of view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5

In [16]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])